default: &default
  adapter: postgresql
  encoding: unicode
  username: devpe007
  password: admin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: registration_management_development

test:
  <<: *default
  database: registration_management_test

production:
  <<: *default
  database: registration_management_troduction
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>